// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: msg_server.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SerMsgId int32

const (
	SerMsgId_ID_FsUnKnown SerMsgId = 0 // 占位
	// 战斗（服务器内部）9001-9999
	SerMsgId_ID_Handshake           SerMsgId = 9001 // 握手
	SerMsgId_ID_FightRoute          SerMsgId = 9003 // 战斗中转 game<->fight
	SerMsgId_ID_ServerClose         SerMsgId = 9004 // 服务器关闭,用来通知其他服
	SerMsgId_ID_Test                SerMsgId = 9005 // 测试消息,可随意更改
	SerMsgId_ID_FsFightTimeoutNtf   SerMsgId = 9006 // 战斗超时
	SerMsgId_ID_FsRefreshMonsterNtf SerMsgId = 9007 // game通知fight刷新怪
	SerMsgId_ID_Heartbeat           SerMsgId = 9008 // game和fight心跳
	SerMsgId_ID_BroadcastMsg        SerMsgId = 9009 // 广播消息
	// 9101-9500 game => fight
	SerMsgId_ID_FsCreateFightReq  SerMsgId = 9101 // 创建战斗
	SerMsgId_ID_FsEnterFightReq   SerMsgId = 9102 // 玩家进入
	SerMsgId_ID_FsLeaveFightReq   SerMsgId = 9103 // 玩家离开战斗
	SerMsgId_ID_FsStartFight      SerMsgId = 9104 // 开始战斗
	SerMsgId_ID_FsAddStageBuff    SerMsgId = 9105 // 添加buff组
	SerMsgId_ID_FsGetFightDataReq SerMsgId = 9106 // 获取战斗数据
	// 9501-9999 fight => game
	SerMsgId_ID_FsCreateFightAck        SerMsgId = 9501
	SerMsgId_ID_FsEnterFightAck         SerMsgId = 9502
	SerMsgId_ID_FsLeaveFightAck         SerMsgId = 9503
	SerMsgId_ID_FsFightResultNtf        SerMsgId = 9504 // 战斗结果推送
	SerMsgId_ID_FsGetFightDataAck       SerMsgId = 9505
	SerMsgId_ID_FsPickItemNtf           SerMsgId = 9506
	SerMsgId_ID_FsPeakBroadcastToGameId SerMsgId = 9507
)

// Enum value maps for SerMsgId.
var (
	SerMsgId_name = map[int32]string{
		0:    "ID_FsUnKnown",
		9001: "ID_Handshake",
		9003: "ID_FightRoute",
		9004: "ID_ServerClose",
		9005: "ID_Test",
		9006: "ID_FsFightTimeoutNtf",
		9007: "ID_FsRefreshMonsterNtf",
		9008: "ID_Heartbeat",
		9009: "ID_BroadcastMsg",
		9101: "ID_FsCreateFightReq",
		9102: "ID_FsEnterFightReq",
		9103: "ID_FsLeaveFightReq",
		9104: "ID_FsStartFight",
		9105: "ID_FsAddStageBuff",
		9106: "ID_FsGetFightDataReq",
		9501: "ID_FsCreateFightAck",
		9502: "ID_FsEnterFightAck",
		9503: "ID_FsLeaveFightAck",
		9504: "ID_FsFightResultNtf",
		9505: "ID_FsGetFightDataAck",
		9506: "ID_FsPickItemNtf",
		9507: "ID_FsPeakBroadcastToGameId",
	}
	SerMsgId_value = map[string]int32{
		"ID_FsUnKnown":               0,
		"ID_Handshake":               9001,
		"ID_FightRoute":              9003,
		"ID_ServerClose":             9004,
		"ID_Test":                    9005,
		"ID_FsFightTimeoutNtf":       9006,
		"ID_FsRefreshMonsterNtf":     9007,
		"ID_Heartbeat":               9008,
		"ID_BroadcastMsg":            9009,
		"ID_FsCreateFightReq":        9101,
		"ID_FsEnterFightReq":         9102,
		"ID_FsLeaveFightReq":         9103,
		"ID_FsStartFight":            9104,
		"ID_FsAddStageBuff":          9105,
		"ID_FsGetFightDataReq":       9106,
		"ID_FsCreateFightAck":        9501,
		"ID_FsEnterFightAck":         9502,
		"ID_FsLeaveFightAck":         9503,
		"ID_FsFightResultNtf":        9504,
		"ID_FsGetFightDataAck":       9505,
		"ID_FsPickItemNtf":           9506,
		"ID_FsPeakBroadcastToGameId": 9507,
	}
)

func (x SerMsgId) Enum() *SerMsgId {
	p := new(SerMsgId)
	*p = x
	return p
}

func (x SerMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_server_proto_enumTypes[0].Descriptor()
}

func (SerMsgId) Type() protoreflect.EnumType {
	return &file_msg_server_proto_enumTypes[0]
}

func (x SerMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerMsgId.Descriptor instead.
func (SerMsgId) EnumDescriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{0}
}

type SerRole int32

const (
	SerRole_client SerRole = 0 // 占位
	SerRole_game   SerRole = 1 // 游戏服
	SerRole_fight  SerRole = 2 // 战斗服
	SerRole_gate   SerRole = 3 // 网关服
)

// Enum value maps for SerRole.
var (
	SerRole_name = map[int32]string{
		0: "client",
		1: "game",
		2: "fight",
		3: "gate",
	}
	SerRole_value = map[string]int32{
		"client": 0,
		"game":   1,
		"fight":  2,
		"gate":   3,
	}
)

func (x SerRole) Enum() *SerRole {
	p := new(SerRole)
	*p = x
	return p
}

func (x SerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_server_proto_enumTypes[1].Descriptor()
}

func (SerRole) Type() protoreflect.EnumType {
	return &file_msg_server_proto_enumTypes[1]
}

func (x SerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerRole.Descriptor instead.
func (SerRole) EnumDescriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{1}
}

type FsUnKnown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FsUnKnown) Reset() {
	*x = FsUnKnown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsUnKnown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsUnKnown) ProtoMessage() {}

func (x *FsUnKnown) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsUnKnown.ProtoReflect.Descriptor instead.
func (*FsUnKnown) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{0}
}

type InterMsgData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   SerRole `protobuf:"varint,1,opt,name=sender,proto3,enum=msg.SerRole" json:"sender,omitempty"`
	Receiver SerRole `protobuf:"varint,2,opt,name=receiver,proto3,enum=msg.SerRole" json:"receiver,omitempty"`
	Data     []byte  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InterMsgData) Reset() {
	*x = InterMsgData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterMsgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterMsgData) ProtoMessage() {}

func (x *InterMsgData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterMsgData.ProtoReflect.Descriptor instead.
func (*InterMsgData) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{1}
}

func (x *InterMsgData) GetSender() SerRole {
	if x != nil {
		return x.Sender
	}
	return SerRole_client
}

func (x *InterMsgData) GetReceiver() SerRole {
	if x != nil {
		return x.Receiver
	}
	return SerRole_client
}

func (x *InterMsgData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InterBaseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId     uint32 `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Content   []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AccountId int64  `protobuf:"varint,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	PacketId  uint32 `protobuf:"varint,4,opt,name=packetId,proto3" json:"packetId,omitempty"`
}

func (x *InterBaseData) Reset() {
	*x = InterBaseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterBaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterBaseData) ProtoMessage() {}

func (x *InterBaseData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterBaseData.ProtoReflect.Descriptor instead.
func (*InterBaseData) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{2}
}

func (x *InterBaseData) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *InterBaseData) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InterBaseData) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *InterBaseData) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

type Handshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{3}
}

func (x *Handshake) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ServerClose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerClose) Reset() {
	*x = ServerClose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerClose) ProtoMessage() {}

func (x *ServerClose) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerClose.ProtoReflect.Descriptor instead.
func (*ServerClose) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{4}
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// 战斗超时
type FsFightTimeoutNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FightId    uint32   `protobuf:"varint,1,opt,name=fightId,proto3" json:"fightId,omitempty"`
	StageId    uint32   `protobuf:"varint,2,opt,name=stageId,proto3" json:"stageId,omitempty"`
	AccountIds []uint32 `protobuf:"varint,3,rep,packed,name=accountIds,proto3" json:"accountIds,omitempty"`
}

func (x *FsFightTimeoutNtf) Reset() {
	*x = FsFightTimeoutNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsFightTimeoutNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsFightTimeoutNtf) ProtoMessage() {}

func (x *FsFightTimeoutNtf) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsFightTimeoutNtf.ProtoReflect.Descriptor instead.
func (*FsFightTimeoutNtf) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{6}
}

func (x *FsFightTimeoutNtf) GetFightId() uint32 {
	if x != nil {
		return x.FightId
	}
	return 0
}

func (x *FsFightTimeoutNtf) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *FsFightTimeoutNtf) GetAccountIds() []uint32 {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I int64           `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	S string          `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	M map[int32]int32 `protobuf:"bytes,3,rep,name=m,proto3" json:"m,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{7}
}

func (x *Test) GetI() int64 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *Test) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Test) GetM() map[int32]int32 {
	if x != nil {
		return x.M
	}
	return nil
}

type FightRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId   uint32 `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FightId uint32 `protobuf:"varint,3,opt,name=fightId,proto3" json:"fightId,omitempty"`
}

func (x *FightRoute) Reset() {
	*x = FightRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FightRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FightRoute) ProtoMessage() {}

func (x *FightRoute) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FightRoute.ProtoReflect.Descriptor instead.
func (*FightRoute) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{8}
}

func (x *FightRoute) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *FightRoute) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FightRoute) GetFightId() uint32 {
	if x != nil {
		return x.FightId
	}
	return 0
}

// 创建战斗
type FsPet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pet *PetUnit `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
}

func (x *FsPet) Reset() {
	*x = FsPet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsPet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsPet) ProtoMessage() {}

func (x *FsPet) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsPet.ProtoReflect.Descriptor instead.
func (*FsPet) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{9}
}

func (x *FsPet) GetPet() *PetUnit {
	if x != nil {
		return x.Pet
	}
	return nil
}

type FsShips struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillPros []uint32           `protobuf:"varint,1,rep,packed,name=skillPros,proto3" json:"skillPros,omitempty"`
	Attrs     map[uint32]float64 `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	CoatId    int32              `protobuf:"varint,3,opt,name=coatId,proto3" json:"coatId,omitempty"`
}

func (x *FsShips) Reset() {
	*x = FsShips{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsShips) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsShips) ProtoMessage() {}

func (x *FsShips) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsShips.ProtoReflect.Descriptor instead.
func (*FsShips) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{10}
}

func (x *FsShips) GetSkillPros() []uint32 {
	if x != nil {
		return x.SkillPros
	}
	return nil
}

func (x *FsShips) GetAttrs() map[uint32]float64 {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *FsShips) GetCoatId() int32 {
	if x != nil {
		return x.CoatId
	}
	return 0
}

type FsUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player    *PlayerUnit         `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Combat    uint32              `protobuf:"varint,2,opt,name=combat,proto3" json:"combat,omitempty"`
	FightType BattleType          `protobuf:"varint,3,opt,name=fightType,proto3,enum=msg.BattleType" json:"fightType,omitempty"`
	ShipLv    uint32              `protobuf:"varint,4,opt,name=ShipLv,proto3" json:"ShipLv,omitempty"`
	Pokers    []uint32            `protobuf:"varint,5,rep,packed,name=pokers,proto3" json:"pokers,omitempty"`
	SkillPro  []uint32            `protobuf:"varint,6,rep,packed,name=skillPro,proto3" json:"skillPro,omitempty"`
	SkillIds  []uint32            `protobuf:"varint,7,rep,packed,name=skillIds,proto3" json:"skillIds,omitempty"`                                                                                 // 额外技能
	Attr      map[uint32]float64  `protobuf:"bytes,8,rep,name=attr,proto3" json:"attr,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`      // 属性  id:num
	Weapons   map[uint32]uint32   `protobuf:"bytes,9,rep,name=Weapons,proto3" json:"Weapons,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 所有武器,lv
	Ships     map[uint32]*FsShips `protobuf:"bytes,10,rep,name=ships,proto3" json:"ships,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`     // 所有防具,lv
	CoatId    int32               `protobuf:"varint,11,opt,name=coatId,proto3" json:"coatId,omitempty"`                                                                                           // 机甲皮肤
}

func (x *FsUser) Reset() {
	*x = FsUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsUser) ProtoMessage() {}

func (x *FsUser) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsUser.ProtoReflect.Descriptor instead.
func (*FsUser) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{11}
}

func (x *FsUser) GetPlayer() *PlayerUnit {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *FsUser) GetCombat() uint32 {
	if x != nil {
		return x.Combat
	}
	return 0
}

func (x *FsUser) GetFightType() BattleType {
	if x != nil {
		return x.FightType
	}
	return BattleType_Battle_None
}

func (x *FsUser) GetShipLv() uint32 {
	if x != nil {
		return x.ShipLv
	}
	return 0
}

func (x *FsUser) GetPokers() []uint32 {
	if x != nil {
		return x.Pokers
	}
	return nil
}

func (x *FsUser) GetSkillPro() []uint32 {
	if x != nil {
		return x.SkillPro
	}
	return nil
}

func (x *FsUser) GetSkillIds() []uint32 {
	if x != nil {
		return x.SkillIds
	}
	return nil
}

func (x *FsUser) GetAttr() map[uint32]float64 {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *FsUser) GetWeapons() map[uint32]uint32 {
	if x != nil {
		return x.Weapons
	}
	return nil
}

func (x *FsUser) GetShips() map[uint32]*FsShips {
	if x != nil {
		return x.Ships
	}
	return nil
}

func (x *FsUser) GetCoatId() int32 {
	if x != nil {
		return x.CoatId
	}
	return 0
}

type FsCreateFightReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId uint32 `protobuf:"varint,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	Extra   []byte `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *FsCreateFightReq) Reset() {
	*x = FsCreateFightReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsCreateFightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsCreateFightReq) ProtoMessage() {}

func (x *FsCreateFightReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsCreateFightReq.ProtoReflect.Descriptor instead.
func (*FsCreateFightReq) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{12}
}

func (x *FsCreateFightReq) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *FsCreateFightReq) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type FsCreateFightAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageId    uint32  `protobuf:"varint,1,opt,name=stageId,proto3" json:"stageId,omitempty"`
	FightId    uint32  `protobuf:"varint,2,opt,name=fightId,proto3" json:"fightId,omitempty"` // 每场战斗唯一id
	Extra      []byte  `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	FightSerId uint32  `protobuf:"varint,4,opt,name=fightSerId,proto3" json:"fightSerId,omitempty"` // 战斗服id
	MapType    MapType `protobuf:"varint,5,opt,name=mapType,proto3,enum=msg.MapType" json:"mapType,omitempty"`
}

func (x *FsCreateFightAck) Reset() {
	*x = FsCreateFightAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsCreateFightAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsCreateFightAck) ProtoMessage() {}

func (x *FsCreateFightAck) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsCreateFightAck.ProtoReflect.Descriptor instead.
func (*FsCreateFightAck) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{13}
}

func (x *FsCreateFightAck) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *FsCreateFightAck) GetFightId() uint32 {
	if x != nil {
		return x.FightId
	}
	return 0
}

func (x *FsCreateFightAck) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *FsCreateFightAck) GetFightSerId() uint32 {
	if x != nil {
		return x.FightSerId
	}
	return 0
}

func (x *FsCreateFightAck) GetMapType() MapType {
	if x != nil {
		return x.MapType
	}
	return MapType_Map_Type_None
}

// 玩家进入战斗
type FsEnterFightReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint32  `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	User     *FsUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pet      *FsPet  `protobuf:"bytes,3,opt,name=pet,proto3" json:"pet,omitempty"`
	Extra    []byte  `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *FsEnterFightReq) Reset() {
	*x = FsEnterFightReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsEnterFightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEnterFightReq) ProtoMessage() {}

func (x *FsEnterFightReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEnterFightReq.ProtoReflect.Descriptor instead.
func (*FsEnterFightReq) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{14}
}

func (x *FsEnterFightReq) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *FsEnterFightReq) GetUser() *FsUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *FsEnterFightReq) GetPet() *FsPet {
	if x != nil {
		return x.Pet
	}
	return nil
}

func (x *FsEnterFightReq) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type FsEnterFightAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint32      `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Objs     []*SceneObj `protobuf:"bytes,2,rep,name=objs,proto3" json:"objs,omitempty"`
	Extra    []byte      `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	Start    bool        `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`                 // 强制开始战斗
	UserId   uint64      `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 玩家id
}

func (x *FsEnterFightAck) Reset() {
	*x = FsEnterFightAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsEnterFightAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEnterFightAck) ProtoMessage() {}

func (x *FsEnterFightAck) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEnterFightAck.ProtoReflect.Descriptor instead.
func (*FsEnterFightAck) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{15}
}

func (x *FsEnterFightAck) GetBattleId() uint32 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *FsEnterFightAck) GetObjs() []*SceneObj {
	if x != nil {
		return x.Objs
	}
	return nil
}

func (x *FsEnterFightAck) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *FsEnterFightAck) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

func (x *FsEnterFightAck) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 玩家离开战斗
type FsLeaveFightReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FightId uint32       `protobuf:"varint,1,opt,name=fightId,proto3" json:"fightId,omitempty"`
	EndType EndFightType `protobuf:"varint,2,opt,name=endType,proto3,enum=msg.EndFightType" json:"endType,omitempty"`
}

func (x *FsLeaveFightReq) Reset() {
	*x = FsLeaveFightReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsLeaveFightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsLeaveFightReq) ProtoMessage() {}

func (x *FsLeaveFightReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsLeaveFightReq.ProtoReflect.Descriptor instead.
func (*FsLeaveFightReq) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{16}
}

func (x *FsLeaveFightReq) GetFightId() uint32 {
	if x != nil {
		return x.FightId
	}
	return 0
}

func (x *FsLeaveFightReq) GetEndType() EndFightType {
	if x != nil {
		return x.EndType
	}
	return EndFightType_End_Fight_None
}

type FsLeaveFightAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FsLeaveFightAck) Reset() {
	*x = FsLeaveFightAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsLeaveFightAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsLeaveFightAck) ProtoMessage() {}

func (x *FsLeaveFightAck) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsLeaveFightAck.ProtoReflect.Descriptor instead.
func (*FsLeaveFightAck) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{17}
}

func (x *FsLeaveFightAck) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// game通知fight刷新怪物
type FsRefreshMonsterNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FightId           uint32   `protobuf:"varint,1,opt,name=fightId,proto3" json:"fightId,omitempty"`
	StageMonsterRefId []uint32 `protobuf:"varint,2,rep,packed,name=stage_monster_ref_id,json=stageMonsterRefId,proto3" json:"stage_monster_ref_id,omitempty"`
	NewAt             bool     `protobuf:"varint,3,opt,name=newAt,proto3" json:"newAt,omitempty"`
}

func (x *FsRefreshMonsterNtf) Reset() {
	*x = FsRefreshMonsterNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsRefreshMonsterNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsRefreshMonsterNtf) ProtoMessage() {}

func (x *FsRefreshMonsterNtf) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsRefreshMonsterNtf.ProtoReflect.Descriptor instead.
func (*FsRefreshMonsterNtf) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{18}
}

func (x *FsRefreshMonsterNtf) GetFightId() uint32 {
	if x != nil {
		return x.FightId
	}
	return 0
}

func (x *FsRefreshMonsterNtf) GetStageMonsterRefId() []uint32 {
	if x != nil {
		return x.StageMonsterRefId
	}
	return nil
}

func (x *FsRefreshMonsterNtf) GetNewAt() bool {
	if x != nil {
		return x.NewAt
	}
	return false
}

// 玩家开始战斗
type FsStartFight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FightId uint32 `protobuf:"varint,1,opt,name=fightId,proto3" json:"fightId,omitempty"`
}

func (x *FsStartFight) Reset() {
	*x = FsStartFight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsStartFight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsStartFight) ProtoMessage() {}

func (x *FsStartFight) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsStartFight.ProtoReflect.Descriptor instead.
func (*FsStartFight) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{19}
}

func (x *FsStartFight) GetFightId() uint32 {
	if x != nil {
		return x.FightId
	}
	return 0
}

// 战斗添加buff组
type FsAddStageBuff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StageBuffIds []uint32 `protobuf:"varint,1,rep,packed,name=stageBuffIds,proto3" json:"stageBuffIds,omitempty"` // stage_buff表id
}

func (x *FsAddStageBuff) Reset() {
	*x = FsAddStageBuff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsAddStageBuff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsAddStageBuff) ProtoMessage() {}

func (x *FsAddStageBuff) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsAddStageBuff.ProtoReflect.Descriptor instead.
func (*FsAddStageBuff) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{20}
}

func (x *FsAddStageBuff) GetStageBuffIds() []uint32 {
	if x != nil {
		return x.StageBuffIds
	}
	return nil
}

// 战斗结果推送
type FsFightResultNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FightId      uint32            `protobuf:"varint,1,opt,name=fightId,proto3" json:"fightId,omitempty"`
	StageId      uint32            `protobuf:"varint,2,opt,name=stageId,proto3" json:"stageId,omitempty"`
	AccountId    uint64            `protobuf:"varint,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Victory      bool              `protobuf:"varint,4,opt,name=victory,proto3" json:"victory,omitempty"`                                                                                                     // 是否胜利
	Reason       EndFightType      `protobuf:"varint,5,opt,name=reason,proto3,enum=msg.EndFightType" json:"reason,omitempty"`                                                                                 // 失败原因
	KillCnt      uint64            `protobuf:"varint,6,opt,name=killCnt,proto3" json:"killCnt,omitempty"`                                                                                                     // 杀怪数量
	FightTime    int64             `protobuf:"varint,7,opt,name=fightTime,proto3" json:"fightTime,omitempty"`                                                                                                 // 战斗时长
	Hp           float32           `protobuf:"fixed32,8,opt,name=hp,proto3" json:"hp,omitempty"`                                                                                                              // 剩余血量
	Chip         uint32            `protobuf:"varint,9,opt,name=chip,proto3" json:"chip,omitempty"`                                                                                                           // 本局获得筹码
	PokerTypes   map[uint32]uint32 `protobuf:"bytes,10,rep,name=pokerTypes,proto3" json:"pokerTypes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`     // pokerType:num 本局获得牌型
	KillMonsters map[uint32]int64  `protobuf:"bytes,11,rep,name=killMonsters,proto3" json:"killMonsters,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // monsterId:num  本局杀怪
	BossHurt     uint64            `protobuf:"varint,12,opt,name=bossHurt,proto3" json:"bossHurt,omitempty"`                                                                                                  // boss伤害
	Extra        []byte            `protobuf:"bytes,13,opt,name=extra,proto3" json:"extra,omitempty"`                                                                                                         // 额外参数 每个玩法不一样
	HpRate       uint32            `protobuf:"varint,14,opt,name=hpRate,proto3" json:"hpRate,omitempty"`                                                                                                      // 剩余血量百分比
}

func (x *FsFightResultNtf) Reset() {
	*x = FsFightResultNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsFightResultNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsFightResultNtf) ProtoMessage() {}

func (x *FsFightResultNtf) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsFightResultNtf.ProtoReflect.Descriptor instead.
func (*FsFightResultNtf) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{21}
}

func (x *FsFightResultNtf) GetFightId() uint32 {
	if x != nil {
		return x.FightId
	}
	return 0
}

func (x *FsFightResultNtf) GetStageId() uint32 {
	if x != nil {
		return x.StageId
	}
	return 0
}

func (x *FsFightResultNtf) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FsFightResultNtf) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *FsFightResultNtf) GetReason() EndFightType {
	if x != nil {
		return x.Reason
	}
	return EndFightType_End_Fight_None
}

func (x *FsFightResultNtf) GetKillCnt() uint64 {
	if x != nil {
		return x.KillCnt
	}
	return 0
}

func (x *FsFightResultNtf) GetFightTime() int64 {
	if x != nil {
		return x.FightTime
	}
	return 0
}

func (x *FsFightResultNtf) GetHp() float32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *FsFightResultNtf) GetChip() uint32 {
	if x != nil {
		return x.Chip
	}
	return 0
}

func (x *FsFightResultNtf) GetPokerTypes() map[uint32]uint32 {
	if x != nil {
		return x.PokerTypes
	}
	return nil
}

func (x *FsFightResultNtf) GetKillMonsters() map[uint32]int64 {
	if x != nil {
		return x.KillMonsters
	}
	return nil
}

func (x *FsFightResultNtf) GetBossHurt() uint64 {
	if x != nil {
		return x.BossHurt
	}
	return 0
}

func (x *FsFightResultNtf) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *FsFightResultNtf) GetHpRate() uint32 {
	if x != nil {
		return x.HpRate
	}
	return 0
}

// 广播多个用户
type BroadcastMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId      uint32   `protobuf:"varint,1,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Content    []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AccountIds []uint64 `protobuf:"varint,3,rep,packed,name=accountIds,proto3" json:"accountIds,omitempty"`
}

func (x *BroadcastMsg) Reset() {
	*x = BroadcastMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMsg) ProtoMessage() {}

func (x *BroadcastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMsg.ProtoReflect.Descriptor instead.
func (*BroadcastMsg) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{22}
}

func (x *BroadcastMsg) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *BroadcastMsg) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *BroadcastMsg) GetAccountIds() []uint64 {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

// 获取战斗数据,存到数据库,断线重连可以继续战斗
type FsGetFightDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FsGetFightDataReq) Reset() {
	*x = FsGetFightDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsGetFightDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsGetFightDataReq) ProtoMessage() {}

func (x *FsGetFightDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsGetFightDataReq.ProtoReflect.Descriptor instead.
func (*FsGetFightDataReq) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{23}
}

type FsGetFightDataAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint32 `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Extra     []byte `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
}

func (x *FsGetFightDataAck) Reset() {
	*x = FsGetFightDataAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsGetFightDataAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsGetFightDataAck) ProtoMessage() {}

func (x *FsGetFightDataAck) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsGetFightDataAck.ProtoReflect.Descriptor instead.
func (*FsGetFightDataAck) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{24}
}

func (x *FsGetFightDataAck) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *FsGetFightDataAck) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type FsPickItemNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[uint32]uint32 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *FsPickItemNtf) Reset() {
	*x = FsPickItemNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsPickItemNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsPickItemNtf) ProtoMessage() {}

func (x *FsPickItemNtf) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsPickItemNtf.ProtoReflect.Descriptor instead.
func (*FsPickItemNtf) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{25}
}

func (x *FsPickItemNtf) GetItems() map[uint32]uint32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type FsPeakBroadcastToGameId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TriggerId uint64 `protobuf:"varint,1,opt,name=TriggerId,proto3" json:"TriggerId,omitempty"`
	CfgId     uint64 `protobuf:"varint,2,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
}

func (x *FsPeakBroadcastToGameId) Reset() {
	*x = FsPeakBroadcastToGameId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_server_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsPeakBroadcastToGameId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsPeakBroadcastToGameId) ProtoMessage() {}

func (x *FsPeakBroadcastToGameId) ProtoReflect() protoreflect.Message {
	mi := &file_msg_server_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsPeakBroadcastToGameId.ProtoReflect.Descriptor instead.
func (*FsPeakBroadcastToGameId) Descriptor() ([]byte, []int) {
	return file_msg_server_proto_rawDescGZIP(), []int{26}
}

func (x *FsPeakBroadcastToGameId) GetTriggerId() uint64 {
	if x != nil {
		return x.TriggerId
	}
	return 0
}

func (x *FsPeakBroadcastToGameId) GetCfgId() uint64 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

var File_msg_server_proto protoreflect.FileDescriptor

var file_msg_server_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x46, 0x73, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x22, 0x72,
	0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x24,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x65, 0x72,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x79, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x1f, 0x0a,
	0x09, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x0d,
	0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x22, 0x1f, 0x0a,
	0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x67,
	0x0a, 0x11, 0x46, 0x73, 0x46, 0x69, 0x67, 0x68, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x4e, 0x74, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0x78, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x69, 0x12, 0x0c, 0x0a,
	0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x12, 0x1e, 0x0a, 0x01, 0x6d,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x65, 0x73,
	0x74, 0x2e, 0x4d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x01, 0x6d, 0x1a, 0x34, 0x0a, 0x06, 0x4d,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x56, 0x0a, 0x0a, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x05, 0x46, 0x73, 0x50,
	0x65, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x65, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x03, 0x70,
	0x65, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x07, 0x46, 0x73, 0x53, 0x68, 0x69, 0x70, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x73, 0x12, 0x2d, 0x0a, 0x05,
	0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x46, 0x73, 0x53, 0x68, 0x69, 0x70, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x61, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x6f, 0x61,
	0x74, 0x49, 0x64, 0x1a, 0x38, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xc2, 0x04,
	0x0a, 0x06, 0x46, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x66, 0x69, 0x67,
	0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x66,
	0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x69, 0x70,
	0x4c, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x68, 0x69, 0x70, 0x4c, 0x76,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x06, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x50, 0x72, 0x6f, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x50, 0x72, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x73,
	0x12, 0x29, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x73, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x32, 0x0a, 0x07, 0x57,
	0x65, 0x61, 0x70, 0x6f, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x46, 0x73, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x73, 0x12,
	0x2c, 0x0a, 0x05, 0x73, 0x68, 0x69, 0x70, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x73, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x69, 0x70,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x68, 0x69, 0x70, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x61, 0x74, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63,
	0x6f, 0x61, 0x74, 0x49, 0x64, 0x1a, 0x37, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3a,
	0x0a, 0x0c, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x46, 0x0a, 0x0a, 0x53, 0x68,
	0x69, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x46, 0x73, 0x53, 0x68, 0x69, 0x70, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x42, 0x0a, 0x10, 0x46, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x46, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x67, 0x68, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x67, 0x68, 0x74, 0x53, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x66, 0x69, 0x67, 0x68, 0x74,
	0x53, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x07, 0x6d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0x83, 0x01,
	0x0a, 0x0f, 0x46, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x46, 0x73, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x03, 0x70, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x46, 0x73, 0x50, 0x65, 0x74, 0x52, 0x03, 0x70, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x46, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x46,
	0x69, 0x67, 0x68, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x6f, 0x62, 0x6a, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4f, 0x62,
	0x6a, 0x52, 0x04, 0x6f, 0x62, 0x6a, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x0f,
	0x46, 0x73, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x45, 0x6e, 0x64, 0x46, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x46, 0x73, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x46, 0x69, 0x67, 0x68, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x76, 0x0a, 0x13, 0x46, 0x73, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4d, 0x6f,
	0x6e, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x74, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x68,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74,
	0x49, 0x64, 0x12, 0x2f, 0x0a, 0x14, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x11, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x66, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x65, 0x77, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x6e, 0x65, 0x77, 0x41, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x46, 0x73, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x46, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x67,
	0x68, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x69, 0x67, 0x68,
	0x74, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x0e, 0x46, 0x73, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x42, 0x75, 0x66, 0x66, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x67, 0x65, 0x42, 0x75,
	0x66, 0x66, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0c, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x42, 0x75, 0x66, 0x66, 0x49, 0x64, 0x73, 0x22, 0xe3, 0x04, 0x0a, 0x10, 0x46, 0x73,
	0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x74, 0x66, 0x12, 0x18,
	0x0a, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x76, 0x69, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x45, 0x6e, 0x64, 0x46, 0x69, 0x67, 0x68, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x69, 0x67, 0x68, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x66, 0x69, 0x67, 0x68, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x68, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x68, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x68, 0x69, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x68, 0x69,
	0x70, 0x12, 0x45, 0x0a, 0x0a, 0x70, 0x6f, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x73, 0x46, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x74, 0x66, 0x2e, 0x50, 0x6f, 0x6b,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x6f,
	0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0c, 0x6b, 0x69, 0x6c, 0x6c,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x46, 0x73, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x4e, 0x74, 0x66, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65,
	0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e,
	0x73, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x73, 0x73, 0x48, 0x75, 0x72,
	0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6f, 0x73, 0x73, 0x48, 0x75, 0x72,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x70, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x70, 0x52, 0x61, 0x74, 0x65, 0x1a,
	0x3d, 0x0a, 0x0f, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3f,
	0x0a, 0x11, 0x4b, 0x69, 0x6c, 0x6c, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x5e, 0x0a, 0x0c, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22,
	0x13, 0x0a, 0x11, 0x46, 0x73, 0x47, 0x65, 0x74, 0x46, 0x69, 0x67, 0x68, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x22, 0x47, 0x0a, 0x11, 0x46, 0x73, 0x47, 0x65, 0x74, 0x46, 0x69, 0x67,
	0x68, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x7e, 0x0a,
	0x0d, 0x46, 0x73, 0x50, 0x69, 0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x74, 0x66, 0x12, 0x33,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x46, 0x73, 0x50, 0x69, 0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x74,
	0x66, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4d, 0x0a,
	0x17, 0x46, 0x73, 0x50, 0x65, 0x61, 0x6b, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x54, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x43, 0x66, 0x67, 0x49, 0x64, 0x2a, 0x95, 0x04, 0x0a,
	0x08, 0x53, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x44, 0x5f,
	0x46, 0x73, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0c, 0x49,
	0x44, 0x5f, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x10, 0xa9, 0x46, 0x12, 0x12,
	0x0a, 0x0d, 0x49, 0x44, 0x5f, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x10,
	0xab, 0x46, 0x12, 0x13, 0x0a, 0x0e, 0x49, 0x44, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x10, 0xac, 0x46, 0x12, 0x0c, 0x0a, 0x07, 0x49, 0x44, 0x5f, 0x54, 0x65,
	0x73, 0x74, 0x10, 0xad, 0x46, 0x12, 0x19, 0x0a, 0x14, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x46, 0x69,
	0x67, 0x68, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4e, 0x74, 0x66, 0x10, 0xae, 0x46,
	0x12, 0x1b, 0x0a, 0x16, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x74, 0x66, 0x10, 0xaf, 0x46, 0x12, 0x11, 0x0a,
	0x0c, 0x49, 0x44, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x10, 0xb0, 0x46,
	0x12, 0x14, 0x0a, 0x0f, 0x49, 0x44, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x4d, 0x73, 0x67, 0x10, 0xb1, 0x46, 0x12, 0x18, 0x0a, 0x13, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x10, 0x8d, 0x47,
	0x12, 0x17, 0x0a, 0x12, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x46, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x10, 0x8e, 0x47, 0x12, 0x17, 0x0a, 0x12, 0x49, 0x44, 0x5f,
	0x46, 0x73, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x10,
	0x8f, 0x47, 0x12, 0x14, 0x0a, 0x0f, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x46, 0x69, 0x67, 0x68, 0x74, 0x10, 0x90, 0x47, 0x12, 0x16, 0x0a, 0x11, 0x49, 0x44, 0x5f, 0x46,
	0x73, 0x41, 0x64, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x42, 0x75, 0x66, 0x66, 0x10, 0x91, 0x47,
	0x12, 0x19, 0x0a, 0x14, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x47, 0x65, 0x74, 0x46, 0x69, 0x67, 0x68,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x10, 0x92, 0x47, 0x12, 0x18, 0x0a, 0x13, 0x49,
	0x44, 0x5f, 0x46, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x67, 0x68, 0x74, 0x41,
	0x63, 0x6b, 0x10, 0x9d, 0x4a, 0x12, 0x17, 0x0a, 0x12, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x46, 0x69, 0x67, 0x68, 0x74, 0x41, 0x63, 0x6b, 0x10, 0x9e, 0x4a, 0x12, 0x17,
	0x0a, 0x12, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x46, 0x69, 0x67, 0x68,
	0x74, 0x41, 0x63, 0x6b, 0x10, 0x9f, 0x4a, 0x12, 0x18, 0x0a, 0x13, 0x49, 0x44, 0x5f, 0x46, 0x73,
	0x46, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x74, 0x66, 0x10, 0xa0,
	0x4a, 0x12, 0x19, 0x0a, 0x14, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x47, 0x65, 0x74, 0x46, 0x69, 0x67,
	0x68, 0x74, 0x44, 0x61, 0x74, 0x61, 0x41, 0x63, 0x6b, 0x10, 0xa1, 0x4a, 0x12, 0x15, 0x0a, 0x10,
	0x49, 0x44, 0x5f, 0x46, 0x73, 0x50, 0x69, 0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x74, 0x66,
	0x10, 0xa2, 0x4a, 0x12, 0x1f, 0x0a, 0x1a, 0x49, 0x44, 0x5f, 0x46, 0x73, 0x50, 0x65, 0x61, 0x6b,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x10, 0xa3, 0x4a, 0x2a, 0x34, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x67,
	0x61, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x66, 0x69, 0x67, 0x68, 0x74, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x67, 0x61, 0x74, 0x65, 0x10, 0x03, 0x32, 0x4e, 0x0a, 0x12, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x38, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67,
	0x12, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x4d,
	0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x28, 0x01, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_server_proto_rawDescOnce sync.Once
	file_msg_server_proto_rawDescData = file_msg_server_proto_rawDesc
)

func file_msg_server_proto_rawDescGZIP() []byte {
	file_msg_server_proto_rawDescOnce.Do(func() {
		file_msg_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_server_proto_rawDescData)
	})
	return file_msg_server_proto_rawDescData
}

var file_msg_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msg_server_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_msg_server_proto_goTypes = []interface{}{
	(SerMsgId)(0),                   // 0: msg.SerMsgId
	(SerRole)(0),                    // 1: msg.SerRole
	(*FsUnKnown)(nil),               // 2: msg.FsUnKnown
	(*InterMsgData)(nil),            // 3: msg.InterMsgData
	(*InterBaseData)(nil),           // 4: msg.InterBaseData
	(*Handshake)(nil),               // 5: msg.Handshake
	(*ServerClose)(nil),             // 6: msg.ServerClose
	(*Heartbeat)(nil),               // 7: msg.Heartbeat
	(*FsFightTimeoutNtf)(nil),       // 8: msg.FsFightTimeoutNtf
	(*Test)(nil),                    // 9: msg.Test
	(*FightRoute)(nil),              // 10: msg.FightRoute
	(*FsPet)(nil),                   // 11: msg.FsPet
	(*FsShips)(nil),                 // 12: msg.FsShips
	(*FsUser)(nil),                  // 13: msg.FsUser
	(*FsCreateFightReq)(nil),        // 14: msg.FsCreateFightReq
	(*FsCreateFightAck)(nil),        // 15: msg.FsCreateFightAck
	(*FsEnterFightReq)(nil),         // 16: msg.FsEnterFightReq
	(*FsEnterFightAck)(nil),         // 17: msg.FsEnterFightAck
	(*FsLeaveFightReq)(nil),         // 18: msg.FsLeaveFightReq
	(*FsLeaveFightAck)(nil),         // 19: msg.FsLeaveFightAck
	(*FsRefreshMonsterNtf)(nil),     // 20: msg.FsRefreshMonsterNtf
	(*FsStartFight)(nil),            // 21: msg.FsStartFight
	(*FsAddStageBuff)(nil),          // 22: msg.FsAddStageBuff
	(*FsFightResultNtf)(nil),        // 23: msg.FsFightResultNtf
	(*BroadcastMsg)(nil),            // 24: msg.BroadcastMsg
	(*FsGetFightDataReq)(nil),       // 25: msg.FsGetFightDataReq
	(*FsGetFightDataAck)(nil),       // 26: msg.FsGetFightDataAck
	(*FsPickItemNtf)(nil),           // 27: msg.FsPickItemNtf
	(*FsPeakBroadcastToGameId)(nil), // 28: msg.FsPeakBroadcastToGameId
	nil,                             // 29: msg.Test.MEntry
	nil,                             // 30: msg.FsShips.AttrsEntry
	nil,                             // 31: msg.FsUser.AttrEntry
	nil,                             // 32: msg.FsUser.WeaponsEntry
	nil,                             // 33: msg.FsUser.ShipsEntry
	nil,                             // 34: msg.FsFightResultNtf.PokerTypesEntry
	nil,                             // 35: msg.FsFightResultNtf.KillMonstersEntry
	nil,                             // 36: msg.FsPickItemNtf.ItemsEntry
	(*PetUnit)(nil),                 // 37: msg.PetUnit
	(*PlayerUnit)(nil),              // 38: msg.PlayerUnit
	(BattleType)(0),                 // 39: msg.BattleType
	(MapType)(0),                    // 40: msg.MapType
	(*SceneObj)(nil),                // 41: msg.SceneObj
	(EndFightType)(0),               // 42: msg.EndFightType
}
var file_msg_server_proto_depIdxs = []int32{
	1,  // 0: msg.InterMsgData.sender:type_name -> msg.SerRole
	1,  // 1: msg.InterMsgData.receiver:type_name -> msg.SerRole
	29, // 2: msg.Test.m:type_name -> msg.Test.MEntry
	37, // 3: msg.FsPet.pet:type_name -> msg.PetUnit
	30, // 4: msg.FsShips.attrs:type_name -> msg.FsShips.AttrsEntry
	38, // 5: msg.FsUser.player:type_name -> msg.PlayerUnit
	39, // 6: msg.FsUser.fightType:type_name -> msg.BattleType
	31, // 7: msg.FsUser.attr:type_name -> msg.FsUser.AttrEntry
	32, // 8: msg.FsUser.Weapons:type_name -> msg.FsUser.WeaponsEntry
	33, // 9: msg.FsUser.ships:type_name -> msg.FsUser.ShipsEntry
	40, // 10: msg.FsCreateFightAck.mapType:type_name -> msg.MapType
	13, // 11: msg.FsEnterFightReq.user:type_name -> msg.FsUser
	11, // 12: msg.FsEnterFightReq.pet:type_name -> msg.FsPet
	41, // 13: msg.FsEnterFightAck.objs:type_name -> msg.SceneObj
	42, // 14: msg.FsLeaveFightReq.endType:type_name -> msg.EndFightType
	42, // 15: msg.FsFightResultNtf.reason:type_name -> msg.EndFightType
	34, // 16: msg.FsFightResultNtf.pokerTypes:type_name -> msg.FsFightResultNtf.PokerTypesEntry
	35, // 17: msg.FsFightResultNtf.killMonsters:type_name -> msg.FsFightResultNtf.KillMonstersEntry
	36, // 18: msg.FsPickItemNtf.items:type_name -> msg.FsPickItemNtf.ItemsEntry
	12, // 19: msg.FsUser.ShipsEntry.value:type_name -> msg.FsShips
	3,  // 20: msg.InterCommonService.InterSendMsg:input_type -> msg.InterMsgData
	3,  // 21: msg.InterCommonService.InterSendMsg:output_type -> msg.InterMsgData
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_msg_server_proto_init() }
func file_msg_server_proto_init() {
	if File_msg_server_proto != nil {
		return
	}
	file_msgtype_proto_init()
	file_msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsUnKnown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterMsgData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterBaseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Handshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerClose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsFightTimeoutNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FightRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsPet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsShips); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsCreateFightReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsCreateFightAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsEnterFightReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsEnterFightAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsLeaveFightReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsLeaveFightAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsRefreshMonsterNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsStartFight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsAddStageBuff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsFightResultNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsGetFightDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsGetFightDataAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsPickItemNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_server_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsPeakBroadcastToGameId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_server_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_server_proto_goTypes,
		DependencyIndexes: file_msg_server_proto_depIdxs,
		EnumInfos:         file_msg_server_proto_enumTypes,
		MessageInfos:      file_msg_server_proto_msgTypes,
	}.Build()
	File_msg_server_proto = out.File
	file_msg_server_proto_rawDesc = nil
	file_msg_server_proto_goTypes = nil
	file_msg_server_proto_depIdxs = nil
}
