// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.22.2
// source: msg_server.proto

package msg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterCommonService_InterSendMsg_FullMethodName = "/msg.InterCommonService/InterSendMsg"
)

// InterCommonServiceClient is the client API for InterCommonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InterCommonServiceClient interface {
	InterSendMsg(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InterMsgData, InterMsgData], error)
}

type interCommonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterCommonServiceClient(cc grpc.ClientConnInterface) InterCommonServiceClient {
	return &interCommonServiceClient{cc}
}

func (c *interCommonServiceClient) InterSendMsg(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InterMsgData, InterMsgData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InterCommonService_ServiceDesc.Streams[0], InterCommonService_InterSendMsg_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InterMsgData, InterMsgData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InterCommonService_InterSendMsgClient = grpc.BidiStreamingClient[InterMsgData, InterMsgData]

// InterCommonServiceServer is the server API for InterCommonService service.
// All implementations must embed UnimplementedInterCommonServiceServer
// for forward compatibility.
type InterCommonServiceServer interface {
	InterSendMsg(grpc.BidiStreamingServer[InterMsgData, InterMsgData]) error
	mustEmbedUnimplementedInterCommonServiceServer()
}

// UnimplementedInterCommonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterCommonServiceServer struct{}

func (UnimplementedInterCommonServiceServer) InterSendMsg(grpc.BidiStreamingServer[InterMsgData, InterMsgData]) error {
	return status.Errorf(codes.Unimplemented, "method InterSendMsg not implemented")
}
func (UnimplementedInterCommonServiceServer) mustEmbedUnimplementedInterCommonServiceServer() {}
func (UnimplementedInterCommonServiceServer) testEmbeddedByValue()                            {}

// UnsafeInterCommonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterCommonServiceServer will
// result in compilation errors.
type UnsafeInterCommonServiceServer interface {
	mustEmbedUnimplementedInterCommonServiceServer()
}

func RegisterInterCommonServiceServer(s grpc.ServiceRegistrar, srv InterCommonServiceServer) {
	// If the following call pancis, it indicates UnimplementedInterCommonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterCommonService_ServiceDesc, srv)
}

func _InterCommonService_InterSendMsg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InterCommonServiceServer).InterSendMsg(&grpc.GenericServerStream[InterMsgData, InterMsgData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InterCommonService_InterSendMsgServer = grpc.BidiStreamingServer[InterMsgData, InterMsgData]

// InterCommonService_ServiceDesc is the grpc.ServiceDesc for InterCommonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterCommonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.InterCommonService",
	HandlerType: (*InterCommonServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InterSendMsg",
			Handler:       _InterCommonService_InterSendMsg_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "msg_server.proto",
}
